export const GET_ACTIVE_GATEWAYS = "GET_ACTIVE_GATEWAYS";
export const GET_INACTIVE_GATEWAYS = "GET_INACTIVE_GATEWAYS";
export const GET_UNACCEPTED_KEYS = "GET_UNACCEPTED_KEYS";
export const SET_LOADING = "SET_LOADING";
export const SET_LOADING_INACTIVE = "SET_LOADING_INACTIVE";
export const SET_SELECTED_GATEWAYS = "SET_SELECTED_GATEWAYS";
export const SET_SELECTED_KEYS = "SET_SELECTED_KEYS";
