export const GET_CONFIG_LIST = "GET_CONFIG_LIST";

export const SET_META_LOADING = "SET_META_LOADING";

export const SET_SELECTED_FILE = "SET_SELECTED_FILE";
export const SET_SELECTED_FILE_META = "SET_SELECTED_FILE_META";
export const SET_UPLOAD_FILE_META = "SET_UPLOAD_FILE_META";
